apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoexp-app
      tier: frontend
  template:
    metadata:
      name: mongoexp-pod
      labels:
        app: mongoexp-app
        tier: frontend
    spec:
      containers:
        - name: mongoexp-container
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: my-db-user
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: my-db-pass
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: db-server
                  key: my-db-server
---
apiVersion: v1
kind: Service
metadata:
  name: mongoexp-service
spec:
  selector:
    app: mongoexp-app
    tier: frontend
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30004
